---
- name: Deploy Docker applications.
  hosts: all

  vars:
    docker_dir: /srv/media

  tasks:
    - name: Copy docker-compose file.
      template:
        src: ./docker-compose{{ project_suffix }}.yaml.enc
        dest: '{{ docker_dir }}/docker-compose.yaml'

    - name: Pull new image versions.
      command: docker compose pull
      args:
        chdir: '{{ docker_dir }}'

    - name: Apply docker-compose file.
      command: docker compose up -d
      args:
        chdir: '{{ docker_dir }}'
