name: Infrastructure and App Deployment

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-infra.yaml
      - terraform/**
      - lambdas/**
  pull_request:
    paths:
      - .github/workflows/deploy-infra.yaml
      - terraform/**
      - lambdas/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  deploy-infrastructure:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 0
      fail-fast: false
      matrix:
        environment:
          - kick-in
          - bata
          - jwg

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # To prevent vague errors, this version needs to be identical to the version of the processing Lambda.
      - name: Set-up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10.5'  # Specify the desired version

      - name: Debug pip and Python version
        run: pip --version
        working-directory: lambdas/photo-processing-lambda

      - name: Install Lambda Prerequisites
        run: pip install -r requirements.txt -t .
        working-directory: lambdas/photo-processing-lambda

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Terraform Init
        id: init
        run: terraform -chdir="./terraform/environments/${{ matrix.environment }}" init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir="./terraform/environments/${{ matrix.environment }}" validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir="./terraform/environments/${{ matrix.environment }}" plan -no-color -lock=false
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v4
        if: github.event_name == 'pull_request' && github.base_ref == github.event.repository.default_branch
        env:
          PLAN: "${{ steps.plan.outputs.stderr }}\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `- **Terraform formatting and style 🖌 \`${{ steps.fmt.outcome }}\`**
            - **Terraform initialization ⚙️ \`${{ steps.init.outcome }}\`**
            - **Terraform plan 📖 \`${{ steps.plan.outcome }}\`**
            - **Terraform validation 🤖 \`${{ steps.validate.outcome }}\`**
            <details><summary>Show plan output</summary>
            \`\`\`
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && steps.plan.outcome != 'failure'
        run: terraform -chdir="./terraform/environments/${{ matrix.environment }}" apply -auto-approve